name: meson CI

on:
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Update system
      run: sudo apt-get update || true
    - name: Install check manually
      run: sudo apt-get install check
    - uses: actions/checkout@v2
    - name: Install meson
      run: pipx install meson==0.53.2
    - name: Install ninja
      run: pipx install ninja==1.9.0.post1
    - name: Install glib-2.0
      run: sudo apt-get install libglib2.0
    - name: Check glib-2.0
      run: ldconfig -p | grep glib-2.0
    - name: Setup meson using threaded plugin
      run: meson -Ddebugprints=false -Dbuildtype=debug -Dsigningplugin=threaded . build_lib
    - name: Compile and run tests
      run: ninja -C build_lib test
    - name: Setup meson
      run: meson -Dbuildtype=debug -Dsigningplugin=unthreaded --reconfigure . build_lib
    - name: Compile and run tests
      run: ninja -C build_lib test
    - name: Install valgrind manually
      run: sudo apt-get install valgrind
    - name: Run valgrind on unittest_common
      run: CK_FORK=no valgrind $GITHUB_WORKSPACE/build_lib/tests/check/unittest_common
    - name: Run valgrind on unittest_signer
      run: CK_FORK=no valgrind $GITHUB_WORKSPACE/build_lib/tests/check/unittest_signer
    - name: Run valgrind on unittest_validator
      run: CK_FORK=no valgrind $GITHUB_WORKSPACE/build_lib/tests/check/unittest_validator
